import type { Metadata } from "next"
import "./globals.css"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { averia } from "@/fonts"

export const metadata: Metadata = {
    title: "Fenamad",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="!scroll-smooth">
            <body className={averia.className}>
                <Navbar />
                <div>
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    )
}
